name: release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    name: ${{ matrix.target.name }}
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        target: [ { target: x86_64-pc-windows-msvc, name: x64 }, { target: i686-pc-windows-msvc, name: x86 } ]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: 'build'
      run: |
        rustup target add ${{ matrix.target.target }}
        cargo build --release --target ${{ matrix.target.target }}
    - name: 'release'
      run: |
        Compress-Archive -Path target\${{ matrix.target.target }}\release\tetris.exe -Destination tetris-${{ matrix.target.name }}.zip
        gh release upload ${{github.event.release.tag_name}} tetris-${{ matrix.target.name }}.zip
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
